version: '3.8'

services:
  mysql-securebank:
    image: mysql:8.0
    container_name: db_securebank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: banco_dados_seguro
    ports:
      - "13306:3306"